---
- hosts: webserver
  remote_user: root
  tasks:
  - name: Add Nginx Repository
    yum: name=epel-release state=latest
  - name: Install Nginx
    yum: name=nginx state=latest
  - name: Change Index
    copy: src=index.html dest=/usr/share/nginx/html/index.html mode=0644
  - name: Nginx start
    service: name=nginx state=started enabled=yes
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
